trigger:
- main

pool:
  name: Continuous Integration
  demands:
  - Agent.OS -equals Linux

steps:
- script: |
    yarn build-lib
    yarn build-demo
  displayName: 'Build'

- script: |
    yarn test-lib
    yarn test-demo
  displayName: 'Test'

- script: |
    yarn publish
  displayName: 'Publish'
