trigger:
- main

pool:
  name: Continuous Integration
  demands:
  - Agent.OS -eq Linux

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli@17
    yarn
    yarn test-lib
  displayName: 'Run tests'

- script: |
    yarn publish
  displayName: 'Publish'
