trigger:
  - main

pool:
  name: Continuous Integration
  demands:
    - Agent.OS -equals Linux

stages:
  - stage: CI
    jobs:
      - job: Build_Test_Publish
        steps:
          - bash: |
              yarn install
            displayName: "Setup"
            env:
              YARN_ENABLE_IMMUTABLE_INSTALLS: false

          - script: |
              yarn build
            displayName: "Build"

          - script: |
              Xvfb -ac :0 -screen 0 1280x1024x16 & export DISPLAY=:0
              yarn test:ci
            displayName: "Test"

          - script: |
              yarn publish
            displayName: "Publish"
