trigger:
- main

pool:
  name: Continuous Integration
  demands:
  - Agent.OS -equals Linux

steps:
- bash: |
    sed 's/file\:dist\/ngx-twcss/0.0.x/g' -i package.json
    yarn
  displayName: 'Setup'

- script: |
    yarn build-lib
    yarn build-demo
  displayName: 'Build'

- script: |
    yarn test-lib
    yarn test-demo
  displayName: 'Test'

- script: |
    yarn publish
  displayName: 'Publish'
