trigger:
- main

pool:
  name: Continuous Integration
  demands:
  - Agent.OS -equals Linux

steps:
- bash: |
    sed 's/file\:dist\/ngx-twcss/0.0.x/g' -i package.json
    yarn
  displayName: 'Setup'
  env:
    YARN_ENABLE_IMMUTABLE_INSTALLS: false

- script: |
    yarn build-lib
    yarn build-demo
  displayName: 'Build'

- script: |
    yarn test-lib --watch=false --no-progress --browsers=Chrome
    yarn test-demo --watch=false --no-progress --browsers=Chrome
  displayName: 'Test'

- script: |
    yarn publish
  displayName: 'Publish'
