trigger:
- main

pool:
  name: Continuous Integration
  demands:
  - Agent.OS -equals Linux

steps:
- bash: |
    sed 's/file\:dist\/ngx-twcss/0.0.x/g' -i package.json
    yarn
  displayName: 'Setup'
  env:
    YARN_ENABLE_IMMUTABLE_INSTALLS: false

- script: |
    yarn build-lib
  displayName: '[Lib] Build'

- script: |
    yarn test-lib:ci
  displayName: '[Lib] Test'

- script: |
    yarn build-demo
  displayName: '[Demo] Build'

- script: |
    yarn test-demo:ci
  displayName: '[Demo] Test'

- script: |
    yarn publish
  displayName: '[Lib] Publish'

# - script: |
#     yarn test-lib:ci
#     yarn test-demo:ci
#   displayName: '[Demo] Publish'
