trigger:
- main

pool:
  name: Continuous Integration
  demands:
  - Agent.OS -equals Linux

steps:
- script: |
    npm install -g @angular/cli@17
    yarn
    yarn test-lib
  displayName: 'Run tests'

- script: |
    yarn publish
  displayName: 'Publish'
