trigger:
  - main

pool:
  name: Continuous Integration
  demands:
    - Agent.OS -equals Linux

variables:
  - name: MajorMinor
    value: "0.0"
  - name: Patch
    value: $[counter(variables.MajorMinor, 67)]
  - name: Release
    value: $(MajorMinor).$(Patch)

name: $(Build.DefinitionName)-${{variables.Release}}

stages:
  - stage: Release
    jobs:
      - job: Build_Test_Publish
        steps:
          - bash: |
              sed 's/file\:dist\/ngx-twcss/0.0.x/g' -i package.json
              sed 's/0.0.0-placeholder/$(Release)/g' -i projects/ngx-twcss/package.json
              echo "Release$(cat projects/ngx-twcss/package.json | grep version)"
              yarn
            displayName: "Setup"
            env:
              YARN_ENABLE_IMMUTABLE_INSTALLS: false

          - script: |
              yarn build
            displayName: "Build"

          - script: |
              Xvfb -ac :0 -screen 0 1280x1024x16 -nolisten unix & export DISPLAY=:0
              yarn test:ci
            displayName: "Test"

          - script: |
              npm config set //registry.npmjs.org/:_authToken=$(authToken)
              cd dist/ngx-twcss
              npm publish
            displayName: "Publish package"
            
          - task: PublishTestResults@2
            displayName: 'Publish test results'
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/TESTS-*.xml'
              searchFolder: '$(Build.SourcesDirectory)'
              mergeTestResults: true
              testRunTitle: 'Test-results-$(Build.DefinitionName)-$(Release)'

          - task: PublishCodeCoverageResults@2
            displayName: 'Publish code coverage'
            inputs:
              summaryFileLocation: '$(Build.SourcesDirectory)/coverage/ngx-twcss/cobertura.xml'
              pathToSources: '$(Build.SourcesDirectory)/coverage/ngx-twcss'