trigger:
  - main

pool:
  name: Continuous Integration
  demands:
    - Agent.OS -equals Linux

stages:
  - stage: Build-Test-Publish
    jobs:
      - job: Build-Test-Publish
        steps:
          - bash: |
              yarn install
            displayName: "Setup"
            # env:
            #   YARN_ENABLE_IMMUTABLE_INSTALLS: false

          - script: |
              yarn build
            displayName: "Build"

          - script: |
              yarn test:ci
            displayName: "Test"

          - script: |
              yarn publish
            displayName: "Publish"
