trigger:
  - main

pool:
  name: Continuous Integration
  demands:
    - Agent.OS -equals Linux

variables:
  - name: MajorMinor
    value: "0.0"
  - name: Patch
    value: $[counter(variables.MajorMinor, 67)]
  - name: Release
    value: $(MajorMinor).$(Patch)

stages:
  - stage: CI
    jobs:
      - job: Build_Test_Publish
        steps:
          - bash: |
              sed 's/file\:dist\/ngx-twcss/0.0.x/g' -i package.json
              sed 's/0.0.66/$(Release)/g' -i projects/ngx-twcss/package.json
              echo "Release $(cat projects/ngx-twcss/package.json | grep version)"
              yarn
            displayName: "Setup"
            env:
              YARN_ENABLE_IMMUTABLE_INSTALLS: false

          - script: |
              yarn build
            displayName: "Build"

          - script: |
              yarn test:ci
            displayName: "Test"

          - script: |
              yarn publish
            displayName: "Publish"
            env:
              NPM_TOKEN: $(authToken)
