trigger:
  branches:
    include:
      - main
      - next
  paths:
    include:
      - src/*

pool:
  name: Ngx-twcss
  demands:
    - Agent.OS -equals Linux

parameters:
  - name: ReleaseTag
    displayName: "Release tag"
    type: string
    default: latest
    values:
      - next
      - latest

stages:
  - stage: CI
    jobs:
      - template: ngx-twcss-demo/job.build.yml@templates

  - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    - stage: CD
      dependsOn: CI
      pool:
        name: Ngx-twcss
        demands:
          - Agent.OS -equals Linux
          - AZP_RUNS -equals ngx-twcss-demo
      jobs:
        - template: ngx-twcss-demo/job.release.yml@templates
