trigger:
  branches:
    include:
      - main
      - next
      - release/*
  paths:
    include:
      - src/*

pool:
  name: Ngx-twcss
  demands:
    - Agent.OS -equals Linux

resources:
  repositories:
    - repository: template
      name: DevOps/Template
      type: git


variables:
  - name: ReleaseTag
    ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      value: latest
    ${{ elseif eq(variables['Build.SourceBranchName'], 'next') }}:
      value: alpha
    ${{ elseif contains(variables['Build.SourceBranch'], 'release') }}:
      value: beta
    ${{ else }}:
      value: insiders

stages:
  - stage: CI
    jobs:
      - template: ngx-twcss-demo/job.build.yml@template

  - stage: CD
    dependsOn: CI
    pool:
      name: Ngx-twcss
      demands:
        - Agent.OS -equals Linux
        - AZP_RUNS -equals ngx-twcss-demo
    jobs:
      - template: ngx-twcss-demo/job.release.yml@template
