trigger:
  branches:
    include:
      - main
      - next
      - fix/*
      - feat/*
      - release/*
  paths:
    include:
      - projects/ngx-twcss/src/*

pool:
  name: Ngx-twcss
  demands:
    - Agent.OS -equals Linux

resources:
  repositories:
    - repository: template
      name: DevOps/Template
      type: git

variables:
  - name: MajorMinor
    value: "0.1"
  - name: Patch
    value: $[counter(variables.MajorMinor, 0)]
  - name: Release
    value: $(MajorMinor).$(Patch)
  - name: ReleaseTag
    ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      value: latest
    ${{ elseif eq(variables['Build.SourceBranchName'], 'next') }}:
      value: next
    ${{ else }}:
      value: nightly

name: $(Build.DefinitionName)-v${{variables.Release}}

stages:
  - stage: CI
    jobs:
    - template: ngx-twcss/job.build-test-publish.yml@template

  - ${{ if or(in(variables['Build.SourceBranchName'], 'main', 'next'), contains(variables['Build.SourceBranch'], 'release/')) }}:
    - stage: CD
      dependsOn: CI
      jobs:
      - template: ngx-twcss/job.release.yml@template
