trigger:
  branches:
    include:
      - main
      - next
      - release/*
  paths:
    include:
      - projects/ngx-twcss/src/*

pool:
  name: Ngx-twcss
  demands:
    - Agent.OS -equals Linux

resources:
  repositories:
    - repository: template
      name: DevOps/Template
      type: git

variables:
  - name: MajorMinor
    value: "0.7"
  - name: Patch
    value: $[counter(variables.MajorMinor, 0)]
  - name: Release
    value: $(MajorMinor).$(Patch)
  - name: ReleaseTag
    ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      value: latest
    ${{ elseif eq(variables['Build.SourceBranchName'], 'next') }}:
      value: alpha
    ${{ elseif contains(variables['Build.SourceBranch'], 'release') }}:
      value: beta
    ${{ else }}:
      value: insiders

name: $(Build.DefinitionName)-v${{variables.Release}}

stages:
  - stage: CI
    jobs:
    - template: ngx-twcss/job.build-test-publish.yml@template

  - stage: CD
    dependsOn: CI
    jobs:
    - template: ngx-twcss/job.release.yml@template
