trigger:
  branches:
    include:
      - master
      - next
      - release/*
  paths:
    include:
      - projects/ngxtw/src/*

pool:
  name: Lab
  demands:
    - Agent.OS -equals Linux

resources:
  repositories:
    - repository: template
      name: DevOps/Template
      type: git

variables:
  - name: MajorMinor
    value: "0.0"
  - name: Patch
    value: $[counter(variables.MajorMinor, 0)]
  - name: Release
    value: $(MajorMinor).$(Patch)
  - name: ReleaseTag
    ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      value: latest
    ${{ elseif eq(variables['Build.SourceBranchName'], 'next') }}:
      value: alpha
    ${{ elseif contains(variables['Build.SourceBranch'], 'release') }}:
      value: beta
    ${{ else }}:
      value: insiders

name: $(Build.DefinitionName)-v${{variables.Release}}

stages:
  - stage: CI
    jobs:
    - template: lab/ngxtw/package/job.build-test-publish.yml@template

  - ${{ if or(in(variables['Build.SourceBranchName'], 'master', 'next'), contains(variables['Build.SourceBranch'], 'release')) }}:
    - stage: CD
      dependsOn: CI
      jobs:
      - template: lab/ngxtw/package/job.release.yml@template
