trigger:
  branches:
    include:
      - master
      - next*
      - dev*
      - feat/*
      - fix/*
  paths:
    include:
      - projects/ngx-twcss/src/*
      - azure-pipelines/*packages.yml

pool:
  name: Ngx-twcss
  demands:
    - Agent.OS -equals Linux

variables:
  - name: MajorMinor
    value: "0.0"
  - name: Patch
    value: $[counter(variables.MajorMinor, 67)]
  - name: Release
    value: $(MajorMinor).$(Patch)
  - name: ReleaseTag
    ${{ if eq(variables['Build.SourceBranchName'], 'next-release') }}:
      value: next
    ${{ else }}:
      value: insiders

name: $(Build.DefinitionName)-v${{variables.Release}}

stages:
  - stage: CI
    jobs:
      - job: Build_Test_Publish
        steps:
          - checkout: self
            persistCredentials: true
            clean: false

          - bash: |
              sed "/file\:dist\/ngx-twcss/d" -i package.json
              if [ -f package-lock.json ]; then \
                echo "Removing package-lock.json"; \
                rm package-lock.json; \
              fi
              npm install
            displayName: "Setup"

          - bash: |
              npm run build:package
            displayName: "Build"

          - bash: |
              npx puppeteer browsers install chrome
              Xvfb -ac :0 -screen 0 1280x1024x16 -nolisten unix & export DISPLAY=:0
              npm run test:package:ci
            displayName: "Test"

          - publish: $(Build.SourcesDirectory)/dist/ngx-twcss
            artifact: drop
            displayName: "Publish artifact"

          - task: PublishTestResults@2
            displayName: "Publish test results"
            inputs:
              testResultsFormat: "JUnit"
              testResultsFiles: "**/TESTS-*.xml"
              searchFolder: "$(Build.SourcesDirectory)"
              mergeTestResults: true
              testRunTitle: "Test-results-$(Build.DefinitionName)-v$(Release)"

          - task: PublishCodeCoverageResults@2
            displayName: "Publish code coverage"
            inputs:
              summaryFileLocation: "$(Build.SourcesDirectory)/coverage/ngx-twcss/cobertura.xml"
              pathToSources: "$(Build.SourcesDirectory)/coverage/ngx-twcss"

  - ${{ if in(variables['Build.SourceBranchName'], 'master', 'next-release', 'develop') }}:
    - stage: CD
      dependsOn: CI
      jobs:
        - job: Release
          steps:
            - checkout: none
            - download: current
              artifact: drop
              displayName: Download artifact

            - ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
                - bash: |
                    sed 's/0.0.0-placeholder/$(Release)/g' -i package.json
                    npm config set //registry.npmjs.org/:_authToken=$(authToken)
                    npm publish
                    npm publish --tag $(echo $(Build.SourceVersion) | cut -c1-7)
                  displayName: "Release v$(Release)"
                  workingDirectory: $(Pipeline.Workspace)/drop
            - ${{ else }}:
                - bash: |
                    release_version="$(Release)-$(ReleaseTag).$(echo $(Build.SourceVersion) | cut -c1-7)"
                    sed "s/0.0.0-placeholder/$release_version/g" -i package.json
                    npm config set //registry.npmjs.org/:_authToken=$(authToken)
                    npm publish --tag $(ReleaseTag)
                  displayName: "Release v$(Release)-$(ReleaseTag)"
                  workingDirectory: $(Pipeline.Workspace)/drop
